version: "3.8"
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    image: jenkins
    container_name: jenkins
    hostname: jenkins
    tty: true
    restart: always
    environment:
      TZ: Asia/Tokyo
      JENKINS_OPTS: '--prefix=/jenkins'
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins:/var/jenkins_home
volumes:
  jenkins:
    driver: local
